name: Go

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"

      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: check-mod-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            check-mod-${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Run tests
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v2.1.0

      - name: Build
        run: go build -v .
