name: x
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
# Common Go workflows from go faster
# See https://github.com/go-faster/x
jobs:
  test:
    uses: go-faster/x/.github/workflows/test.yml@main
    with:
      enable-386: false
      enable-arm64: false
      # submodules: true
      go: stable
  cover:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
          cache: false
      - name: Run tests with coverage
        run: make coverage
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

  cover-send:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: cover
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage
      - name: Send coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: profile.out
          fail_ci_if_error: false
  lint:
    uses: go-faster/x/.github/workflows/lint.yml@main
    with:
      go: stable
  commit:
    uses: go-faster/x/.github/workflows/commit.yml@main
  codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: go-faster/x/.github/workflows/codeql.yml@main
    with:
      go: stable
